### ISSUE TITLE
Wechaty 社区 “暑期2021” 项目列表

### ISSUE THREAD

**Issue by Roxanne718** [wechaty/summer-of-wechaty#79]
- [ ] （难度：低）开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序 #78 
- [ ] （难度：中）基于 Itchat 为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet #75 
- [ ] （难度：中）开发支持电信运营商 5G Chatbot / RCS 的 Wechaty 接入 Puppet 模块 #74 
- [ ] （难度：低）基于开放 API 封装 Wechaty 接口下的飞书聊天机器人 #38

**Comment by wj-Mcat** [comment]
补充项目：

- [ ] (难度：中) 基于 WeChatExtension-ForMac 为 Wechaty 实现Mac版本Puppet https://github.com/wechaty/summer-of-wechaty/issues/58

**Comment by huan** [comment]
补充项目：

- [ ] 基与 Blessed 的 Wechaty 命令行文本客户端软件（防IRC）, @huan #80

**Comment by wj-Mcat** [comment]
补充二师兄项目：

- [ ] (难度：中) 基于Wechaty 开发开源的二师兄社群逗乐机器人, @Valerieeeee @wj-Mcat

**Comment by lijiarui** [comment]
## 期初报告

项目名称 | PR | 期初报告
-- | -- | --
开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序 | https://github.com/wechaty/wechaty.js.org/pull/1090 |  
基于 Itchat 为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet | https://github.com/wechaty/wechaty.js.org/pull/1069 | [OSPP 2021-期初报告-基于 Itchat 为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet](https://wechaty.js.org/2021/07/13/ospp-plan-wechaty-itchat-puppet/)
开发支持电信运营商 5G Chatbot / RCS 的 Wechaty 接入 Puppet 模块 | https://github.com/wechaty/wechaty.js.org/pull/1097 |  
基于开放 API 封装 Wechaty 接口下的飞书聊天机器人 | https://github.com/wechaty/wechaty.js.org/pull/1085 |  
基与 Blessed 的 Wechaty 命令行文本客户端软件（仿IRC） | https://github.com/wechaty/wechaty.js.org/pull/1080 | [OSPP 2021-期初报告-基于 Blessed 的 Wechaty 命令行文本客户端软件](https://wechaty.js.org/2021/07/14/ospp-plan-blessed-cli/)
基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善 | https://github.com/wechaty/wechaty.js.org/pull/1074 | [OSPP 2021-期初报告-基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善](https://wechaty.js.org/2021/07/14/ospp-plan-wechaty-matrix/)
开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块 | https://github.com/wechaty/wechaty.js.org/pull/1051 | [OSPP 2021-期初报告-开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块](https://wechaty.js.org/2021/07/11/ospp-plan-qq-puppet/)
基于 Wechaty Puppet Official Account 项目的用户与消息等基础功能的完善 | https://github.com/wechaty/wechaty.js.org/pull/1109 |  
基于Wechaty 开发开源的二师兄社群逗乐机器人 | https://github.com/wechaty/wechaty.js.org/pull/1078 | [OSPP 2021-期初报告-基于 Wechaty 开发开源的二师兄社群逗乐机器人](https://wechaty.js.org/2021/07/13/ospp-plan-wechaty-piggy-bro/)

**Comment by MustangYM** [comment]
很遗憾，因为开发WeChatExtension这个项目，我的微信号被永久封禁了，能临时登录看到消息，但无法回复消息，这个项目也不再维护，给大家带来麻烦了，抱歉了。
| |
mustangym
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年07月18日 ***@***.***> 写道：

期初报告
| 项目名称 | PR | 期初报告 |
| 开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序 | wechaty/wechaty.js.org#1090 |   |
| 基于 Itchat 为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet | wechaty/wechaty.js.org#1069 | OSPP 2021-期初报告-基于 Itchat 为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet |
| 开发支持电信运营商 5G Chatbot / RCS 的 Wechaty 接入 Puppet 模块 | wechaty/wechaty.js.org#1097 |   |
| 基于开放 API 封装 Wechaty 接口下的飞书聊天机器人 | wechaty/wechaty.js.org#1085 |   |
| 基与 Blessed 的 Wechaty 命令行文本客户端软件（仿IRC） | wechaty/wechaty.js.org#1080 | OSPP 2021-期初报告-基于 Blessed 的 Wechaty 命令行文本客户端软件 |
| 基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善 | wechaty/wechaty.js.org#1074 | OSPP 2021-期初报告-基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善 |
| 开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块 | wechaty/wechaty.js.org#1051 | OSPP 2021-期初报告-开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块 |
| 基于 Wechaty Puppet Official Account 项目的用户与消息等基础功能的完善 | wechaty/wechaty.js.org#1109 |   |
| 基于Wechaty 开发开源的二师兄社群逗乐机器人 | wechaty/wechaty.js.org#1078 | OSPP 2021-期初报告-基于 Wechaty 开发开源的二师兄社群逗乐机器人 |

**Comment by lijiarui** [comment]
## 期中报告

项目名称 | 组委会期中报告提交情况 | 期中报告
-- | -- | --
[开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序](https://github.com/wechaty/summer/issues/78) |  | 
[基于 Itchat 为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet](https://github.com/wechaty/summer/issues/75) |  | 
[开发支持电信运营商 5G Chatbot / RCS 的 Wechaty 接入 Puppet 模块](https://github.com/wechaty/summer/issues/74) |  |  
[基于开放 API 封装 Wechaty 接口下的飞书聊天机器人](https://github.com/wechaty/summer-of-wechaty/issues/38) |  |
[基与 Blessed 的 Wechaty 命令行文本客户端软件（仿IRC）](https://github.com/wechaty/summer/issues/80) |  | 
[基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善](https://github.com/wechaty/summer/issues/59) |  | 
[开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块](https://github.com/wechaty/summer/issues/81) |  | 
[基于 Wechaty Puppet Official Account 项目的用户与消息等基础功能的完善](https://github.com/wechaty/summer/issues/82) |  |  
[基于Wechaty 开发开源的二师兄社群逗乐机器人](https://github.com/wechaty/summer/issues/83) |  |

**Comment by lijiarui** [comment]
# Wechaty 社区期中答辩（Mid-term Demo Day）通知

8月28日，举办 OSPP 的 Mid-term Demo Day， 导师和学生会在线上进行期中汇报。提交的期中报告包括 Mid-term Demo Day 的视频和期中报告内容总结

## 学生开发者

### 1. 期中 Demo Day 视频

每位开发者需要进行中期的展示，视频将添加至博客、提交到组委会中，并剪辑成完成的路演日视频，向全社区展示，吸引更多的开发者参与到对应的项目中：

- 提交3-5分钟的、有真人出镜（视频会议软件录制）的、基于PPT的展示。
- 提交不限时长的、有真人出镜（视频会议软件录制）的 Live Code。

学生要在8月26日之前将视频链接回复在对应项目的 Github Issue 下面进行提交，视频由同学们直接上传到Youtube / B站中，并直接将视频的链接和将视频以iframe方式附在各个博客中：

- 视频需要上传到 youtube 中，并联系 [Huan](https://wechaty.js.org/contributors/huan/) 添加到 wechaty 的 playlist 中。
- 考虑到国内用户，可以上传到 bilibili 或者腾讯视频中

可以参考去年优秀学生突出贡献奖获得者[江姗姗](https://wechaty.js.org/contributors/univerone/)的视频：

- [期中汇报视频](https://www.bilibili.com/video/BV1vT4y157x5/)
- [Live Coding 视频](https://www.bilibili.com/video/BV1ih411d75h)

### 2. 期中报告

在8月30日前，以Pull Requests形式在[wechaty.js.org Repo](https://github.com/wechaty/wechaty.js.org)中提交博客。

- 标题： `OSPP 2021-期中报告-你的标题`
- 文件名： `2021-XX-XX-ospp-mid-term-XX`
- 报告 category 为：`project`, `ospp`
- 报告 tag 至少包括：`summer-of-wechaty`,`summer-2021`,`ospp`,`ospp-2021`,`mid-term`，`ospp`
- 报告内容至少包括：
  - 项目信息
    - 项目名称
    - 方案描述
    - 时间规划
  - 项目进度
    - 已完成工作
    - 遇到的问题及解决方案
    - 后续工作安排
  - 项目成果
    - 期中汇报的视频，可以参考 [使用jekyll include在wechaty博客中快速插入视频](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
    - Live Coding/Demo 视频

可以完整复制本文对应的Markdown作为博客内容模板，但也可添加更多的补充信息。

```markdown
“[开源软件供应链点亮计划-暑期2021](https://summer.iscas.ac.cn)”（以下简称 暑期2021）是由中科院软件所与 openEuler 社区共同举办的一项面向高校学生的暑期活动。旨在鼓励在校学生积极参与开源软件的开发维护，促进国内优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。 学生可自主选择感兴趣的项目进行申请，并在中选后获得该软件资深维护者（社区导师）亲自指导的机会。 根据项目的难易程度和完成情况，参与者还可获取“开源软件供应链点亮计划-暑期2021”活动奖金和奖杯。

本项目 [项目名称] 系 暑期2021 支持的开源项目。

## [项目名称]信息

- 导师：[导师名称]  
- 学生：[学生名称]  
- 项目介绍：[Github Issue 链接，如 https://github.com/wechaty/summer/issues/74]  

- 项目名称：  
- 方案描述：  
- 时间规划：  

## 项目进度

- 已完成工作：  
  *根据原定方案和时间规划，描述当前已有的工作成果*  
- 遇到的问题及解决方案：   
  *可以侧重描述总结与心得*  
- 后续工作安排：  
  *描述是否需要调整工作计划等*  

## 项目成果

项目仓库: <https://github.com/XX/XX>  

### live coding视频:

{% include iframe.html src="视频链接" %}

### PPT展示视频:

{% include iframe.html src="视频链接" %}

### 项目PPT:

{% include iframe.html src="pdf链接" %}

## 联系我们

- 项目链接：[Github Issue 链接，如 https://github.com/wechaty/summer/issues/74]  
- 联系方式：
```

### 3. OSPP 2020 学生期中报告参考：

- [基于开放 API 封装 Wechaty 接口下的飞书聊天机器人：期中](https://wechaty.js.org/2020/08/19/wechaty-puppet-lark-mid-term-blog/)
- [暑期2020 编写一个“每日一句”插件 POC 成果展示](https://wechaty.js.org/2020/08/15/wechaty-words-per-day-plugin-mid-term/)
- [暑期2020 基于python-wechaty的群聊助手机器人 POC 成果展示](https://wechaty.js.org/2020/08/14/python-wechaty-groupchat-assistant-bot-poc/)
- [暑期2020 基于 RPA 封装 Wechaty 接口下的快手聊天机器人 中期报告](https://wechaty.js.org/2020/08/20/wechaty-puppet-kuaishou-mid-term/)
- [Wechaty Java 移植组件开发](https://wechaty.js.org/2020/08/17/java-wechaty-transplant-midpoc/)

## 社区导师

### 1. “暑期2021”组委会评审报告

08月16日 - 08月22日期间，将评审报告在组委会的 Gitlab 上的 Issue 中提交，并配合组委会进行中期审核。

### 2. Wechaty 社区中期博客评审

在8月30日前以Pull Requests形式在wechaty.github.io的学生对应博客下，补充评审结果的相关信息。

可以完整复制本文对应的Markdown作为博客内容模板，但也可添加更多的补充信息。

```markdown
## 评审对象

- 评审内容：*中期报告|结项报告*
- 提交人：*学生姓名*

## 评审结果

- 项目完成度：*评价学生是否按照原定方案实施项目，以及完成情况如何*
- 学生参与度：*评价学生在项目实施过程中是否积极参与*
- 代码贡献量：*评价学生在该项目中，为开源项目贡献的代码量*
- 综合评价及建议：*总结性评价，并给出改进建议*
- 最终评审结果：“通过” 或者 “不通过” （“不通过” 意为着项目终止，且学生将无法获得相应的奖金）
```

**Comment by Roxanne718** [comment]
# Wechaty 社区结项答辩（Final-term Demo Day）通知

10月9日，举办 OSPP 的 Final-term Demo Day， 导师和学生会在线上进行结项汇报。

参考链接：

- [开源之夏 2021 指导手册](https://wechaty.js.org/2021/06/24/summer-wechaty-guide/)
- [Wechaty 社区开源协作最佳实践指南](https://wechaty.js.org/2021/06/23/the-wechaty-way/)
- [在 Wechaty Meeting Notes 中注册确认参会](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.5ztnno5qivcb)

## 学生开发者

学生开发者需要在9月30日之前提交如下材料，作为结项审核内容。

### 1. 结项 Demo Day 视频

每位开发者需要进行结项展示，视频将添加至博客、提交到组委会中，并剪辑成完成的路演日视频，向全社区展示，吸引更多的开发者参与到对应的项目中：

- 提交3-5分钟的、有真人出镜（视频会议软件录制）的、基于PPT的展示。
- 提交不限时长的、有真人出镜（视频会议软件录制）的 Live Code。

**在9月30日之前将视频链接回复在对应项目的 Github Issue 下面进行提交**，视频由同学们直接上传到Youtube / B站中，并直接将视频的链接和将视频以iframe方式附在各个博客中：

- 视频需要上传到 youtube 中，并联系 [Huan](https://wechaty.js.org/contributors/huan/) 添加到 wechaty 的 playlist 中。
- 考虑到国内用户，可以上传到 bilibili 或者腾讯视频中

可以参考去年优秀学生突出贡献奖获得者[江姗姗](https://wechaty.js.org/contributors/univerone/)的视频：

- [结项汇报视频](https://www.bilibili.com/video/BV1pf4y1D71F?zw)
- [Live Coding 视频](https://www.bilibili.com/video/BV1ih411d75h?zw)

### 2. 结项报告

**9月30日**前，以Pull Requests形式在[wechaty.js.org Repo](https://github.com/wechaty/wechaty.js.org)中提交博客。

- 标题： `OSPP 2021-结项报告-你的标题`
- 文件名： `2021-XX-XX-ospp-final-term-XX`
- 报告 category 为：`project`, `ospp`
- 报告 tag 至少包括：`summer-of-wechaty`,`summer-2021`,`ospp`,`ospp-2021`,`final-term`
- 报告内容至少包括：
  - 项目信息
    - 项目名称
    - 方案描述
    - 时间规划
  - 项目总结
    - 项目成果
    - 遇到的问题及解决方案
    - 项目展望
  - 项目展示
    - 结项汇报的视频，可以参考 [使用jekyll include在wechaty博客中快速插入视频](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
    - Live Coding/Demo 视频

可以完整复制本文对应的Markdown作为博客内容模板，但也可添加更多的补充信息。

```markdown
“[开源软件供应链点亮计划-暑期2021](https://summer.iscas.ac.cn)”（以下简称 暑期2021）是由中科院软件所与 openEuler 社区共同举办的一项面向高校学生的暑期活动。旨在鼓励在校学生积极参与开源软件的开发维护，促进国内优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。 学生可自主选择感兴趣的项目进行申请，并在中选后获得该软件资深维护者（社区导师）亲自指导的机会。 根据项目的难易程度和完成情况，参与者还可获取“开源软件供应链点亮计划-暑期2021”活动奖金和奖杯。

本项目 [项目名称] 系 暑期2021 支持的开源项目。

## [项目名称]信息

- 导师：[导师名称]  
- 学生：[学生名称]  
- 项目介绍：[Github Issue 链接，如 https://github.com/wechaty/summer/issues/74]  

- 项目名称：  
- 方案描述：  
- 时间规划：  

## 项目总结

- 项目成果：  
  *根据原定方案和时间规划，描述当前已有的工作成果*  
- 遇到的问题及解决方案：   
  *可以侧重描述总结与心得*  
- 项目展望：  
  *描述对该项目后续开发的建议*  

## 项目成果

项目仓库: <https://github.com/XX/XX>  

### live coding视频:

{% include iframe.html src="视频链接" %}

### PPT展示视频:

{% include iframe.html src="视频链接" %}

### 项目PPT:

{% include iframe.html src="pdf链接" %}

## 联系我们

- 项目链接：[Github Issue 链接，如 https://github.com/wechaty/summer/issues/74]  
- 联系方式：
```

### 3. OSPP 2020 学生结项报告参考：

- [暑期2020 基于开放 API 封装 Wechaty 接口下的飞书聊天机器人](https://wechaty.js.org/2020/09/30/wechaty-puppet-lark-final-blog/)
- [暑期2020 编写一个“每日一句”插件 结项报告](https://wechaty.js.org/2020/09/26/wechaty-words-per-day-plugin-final/)
- [暑期2020 基于python-wechaty的群聊助手机器人](https://wechaty.js.org/2020/08/14/chassist-bot-final/)
- [暑期2020 基于Python-wechaty建立一个斗图机器人](https://wechaty.js.org/2020/09/27/python-wechaty-meme-bot-final/)
- [暑期2020 基于 RPA 封装 Wechaty 接口下的快手聊天机器人](https://wechaty.js.org/2020/08/20/wechaty-puppet-kuaishou-mid-term/)

## 社区导师

### 1. “暑期2021”组委会评审报告

10月1日 - 10月14日期间，将评审报告在组委会的 Gitlab 上的 Issue 中提交，并配合组委会进行结项审核。

### 2. Wechaty 社区结项博客评审

在10月14日前以Pull Requests形式在wechaty.github.io的学生对应博客下，补充评审结果的相关信息。

可以完整复制本文对应的Markdown作为博客内容模板，但也可添加更多的补充信息。

```markdown
## 评审对象

- 评审内容：*中期报告|结项报告*
- 提交人：*学生姓名*

## 评审结果

- 项目完成度：*评价学生是否按照原定方案实施项目，以及完成情况如何*
- 学生参与度：*评价学生在项目实施过程中是否积极参与*
- 代码贡献量：*评价学生在该项目中，为开源项目贡献的代码量*
- 综合评价及建议：*总结性评价，并给出改进建议*
- 最终评审结果：“通过” 或者 “不通过” （“不通过” 意为着项目终止，且学生将无法获得相应的奖金）
```

**Comment by lijiarui** [comment]
## 期末报告

项目名称 | 组委会期末报告 | 导师审核 | 期末报告 PR | 期末报告
-- | :-: | :-: | -- | --
[开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序](https://github.com/wechaty/summer/issues/78) | ✅ |  |    |  |  |  `|
[基于 Itchat 为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet](https://github.com/wechaty/summer/issues/75) |    | |    | |  |  `|
[开发支持电信运营商 5G Chatbot / RCS 的 Wechaty 接入 Puppet 模块](https://github.com/wechaty/summer/issues/74) |    | |    | |   |  `|
[基于开放 API 封装 Wechaty 接口下的飞书聊天机器人](https://github.com/wechaty/summer-of-wechaty/issues/38) | ✅ | |  |  `|
[基与 Blessed 的 Wechaty 命令行文本客户端软件（仿IRC）](https://github.com/wechaty/summer/issues/80) | ✅ | |    | |  |  `|
[基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善](https://github.com/wechaty/summer/issues/59) | ✅ | |    | |  |  `|
[开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块](https://github.com/wechaty/summer/issues/81) | ✅ | |    |  |  |  `|
[基于 Wechaty Puppet Official Account 项目的用户与消息等基础功能的完善](https://github.com/wechaty/summer/issues/82) |    | |    |   |   |  `|
[基于Wechaty 开发开源的二师兄社群逗乐机器人](https://github.com/wechaty/summer/issues/83) | ✅ |  |    |  |  |  `|
